services:
  - type: web
    name: youtube-downloader-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BATBIN_API_KEY
        sync: false
      - key: MAX_VIDEO_SIZE
        value: "2000"
      - key: DEFAULT_RESOLUTION
        value: "720"
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 20
